accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns =[ 
    path('',views.welcome, name="welcome"),
    path('login/',views.login_user, name="login"),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('logout', views.logout_user, name="logout"),
    ]

lib/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('library/', include('library.urls')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
#from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Student(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    course = models.CharField(max_length=20)
    #id = PhoneNumberField(null=False, blank=False, unique=True)
    

    def __str__(self):
        return str(self.user)

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms



# Sign Up Form
class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length= 15, help_text= '*' )
    first_name = forms.CharField(max_length = 30, help_text= '*')
    last_name = forms.CharField(max_length = 30, required=False) #help_text= 'Optional')
    email = forms.EmailField(max_length=200) #help_text = 'Enter valid e-mail address')
    course = forms.CharField(max_length= 35, required= True , help_text='*')

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'course',
        ]

        widgets = {
                'username': forms.TextInput(attrs={"class": "form-input","placeholder":"Enter your username"}),
                'first_name': forms.TextInput(attrs={'class': 'form-input','placeholder':'Enter your first name'}),
                'last_name': forms.TextInput(attrs={'class': 'form-input','placeholder':'Enter your last name'}),
                'email': forms.EmailInput(attrs={'class': 'form-input','placeholder':'Enter your email address'}),
                'course': forms.TextInput(attrs={'class': 'form-input','placeholder':'Enter your course'}),
                'password': forms.TextInput(attrs={'class': 'form-input','placeholder':'Enter your password'}),
                'password1': forms.TextInput(attrs={'class': 'form-input','placeholder':'Confirm your password'}),
            }

        labels = {
            'username':'',
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import SignUpForm
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.

def welcome(request):
    return render(request, 'authenticate/welcome.html', {})


class SignUpView(generic.CreateView):
    form_class = SignUpForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('accounts:login')

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('library:book_overview')
        else:
            messages.success(request, ("There was an error logging in, please try again...."))
            return redirect('accounts:login')
    else:
        return render(request, 'authenticate/login.html',{})

def logout_user(request):
    logout(request)
    messages.success(request, ("you logged out"))
    return redirect("accounts:login")   

accounts/templates/authenticate/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LogIn</title>
</head>
<body>
    {% extends "regbase.html" %}
    {% load static %}
    {% block page_content %}
     <br><br>
    <center>
        <h1>Welcome to GroupMEve Sample Library</h1>
        <h2>LogIn Below</h3>
        <br><br>
        <p> {% if messages %}
             {% for message in messages %}
              {{message}}
             {% endfor %}
            {% endif %}
       </p>
        <div class="login">
            <br><br>
            <form method= POST>
                {% csrf_token %}
                <input type="text" name="username" class="form-input" placeholder="Input your Username here">
                <br>
                <input type="password" name="password" class="form-input" placeholder="Input your Password here">
                <br>
                <input type="submit" value="Login" class="form-button">

                <p>Don't have an account?<a href="{% url 'accounts:signup' %}">Register</a> </p>
                <p>For Library<a href="{% url 'admin:index' %}" > Admin</a></p>
            </form>
        </div>
        


    </center>
    {% endblock %}
</body>
</html>

accounts/templates/authenticate/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Welcome to GroupMSample Library

    your are a.....
    <a href="{% url 'admin:index' %}">Librarian</a>
    <a href="{% url 'accounts:login' %}">Student</a>
</body>
</html>