accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns =[ 
    path('',views.welcome, name="welcome"),
    path('login/',views.login_user, name="login"),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('logout', views.logout_user, name="logout"),
    ]

lib/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('library/', include('library.urls')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path
from . import views
app_name = 'library'

urlpatterns = [
    path("",views.book_overview,name="book_overview"),
    path("<int:pk>/",views.book_detail,name="book_detail"),
    path("<int:pk>/borrow/", views.borrow, name="borrow"),
    path("activity", views.activity, name="activity"),
    path("urlmessage", views.urlmessage, name="message"),
    ]

lib/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Document
        {% block title %}
        {% endblock%}
    </title>
</head>
<body>
    <nav class="navbar">
        <a class="maina" font-size="60px" href="{% url 'library:book_overview' %}">Bookshelf</a>
        <a class="maina"  font-size="60px" href="{% url 'library:activity' %}">Activity</a>
        {% if user.is_authenticated %}
        <a class="maina" font-size="60px" href="{% url 'accounts:login' %}">LogOut</a>
        {% else %}
        <a class="maina" font-size="60px" href="{% url 'accounts:login' %}">Login</a>
        {% endif%}
        <a class="maina" font-size="60px" href=""></a>
        <p>Welcome,{{user.username}}</p>
    </nav>
    <div>
        {% block page_content %}
        {% endblock %}
    </div>
</body>
</html>

lib/templates/regbase.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% block title %}
            {% endblock%}
        </title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        {% load static %}
        <link  rel="stylesheet" href="{% static 'regbase.css' %}">
    </head>
  
    <body bgcolor="#F9FBE7">

  
        <div>
            {% block page_content %}

            {% endblock%}
        </div>

    </body>