lib/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('library/', include('library.urls')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path
from . import views
app_name = 'library'

urlpatterns = [
    path("",views.book_overview,name="book_overview"),
    path("<int:pk>/",views.book_detail,name="book_detail"),
    path("<int:pk>/borrow/", views.borrow, name="borrow"),
    path("activity", views.activity, name="activity"),
    path("urlmessage", views.urlmessage, name="message"),
    ]

library/models.py
#from datetime import datetime
from django.db import models
from datetime import date, datetime, timedelta

# Create your models here.


class Book(models.Model):
    STATUS = (
        ('Available', 'Available'),
        ('Unavailable', 'Unavailable'),
    )
    title            = models.CharField(max_length=40)
    publication_date = models.DateField(auto_now=True)
    subject_area     = models.CharField(max_length=15)
    author           = models.CharField(max_length=40)
    description      = models.TextField()
    cover_photo      = models.ImageField(null=True, blank=True, upload_to='static/images/')
    status           = models.CharField(max_length=15, choices=STATUS, default='Available')

    def __str__(self) :
        return self.title





class Borrow(models.Model):
    FINE = (
        ("None", "None"),
        ("5000", "5000"),
        ("10000", "10000"),
        ("15000", "15000"),
    )
    book_title    = models.ForeignKey('Book', on_delete=models.CASCADE)
    borrow_date   = models.DateField(auto_now=True)
    email_address = models.EmailField('Email Field')
    fine          = models.CharField(max_length=6, choices=FINE, default='None')

    def __str__(self):
        return self.book_title.title
    # use this in table that will leep track of days

    
    

    @property
    def days_remaining(self):
        today = date.today()
        days_togo= self.return_date - today
        return days_togo.days

    @property
    def return_date(self):
        that_date = self.borrow_date + timedelta(days=3)
        return that_date

    @property
    def Fine(self):
        dafine = self.fine
        if self.days_remaining <= -3:
            dafine = "5000"

        elif self.days_remaining <= -10:
            dafine = "10000"
        
        elif self.days_remaining <= -15:
            dafine = "15000"

        else:
            dafine = "None"

        return dafine
        

        # today = date.today()
        # if (self.return_date < today):
        #     if (today - self.return_date) >= timedelta(days=3)
        #     returned = "PAST"
        # return returned

library/forms.py
from django import forms
from django.forms import ModelForm
from .models import Borrow


class BorrowForm(ModelForm):
    class Meta:
        model = Borrow
        fields = ['book_title',
            'email_address',
            ]
        # widgets = {
        #     'book_title': forms.TextInput(attrs={"class": "form-input","placeholder":"Select the book your taking"}),
        #      'email_address': forms.EmailInput(attrs={'class': 'form-input','placeholder':'Enter your email address eg someone@gmail.com'}),
         #}
        labels = {
            'book_title':'',
            'email_address':''
        }

library/views.py
from django.shortcuts import render, redirect
from .models import Book, Borrow
#from Borrow import Days_remainng
from .models import Book
from .forms import BorrowForm
from django.contrib import messages
from django.urls import reverse_lazy
#from datetime import date,timedelta

# Create your views here.
def book_overview(request):
    books = Book.objects.all().order_by('-publication_date')
    context = {
        'books': books
    }
    return render(request, 'book_temps/book_overview.html', context)

def book_detail(request, pk):
    detail = Book.objects.get(pk= pk)
    context = {
        'detail': detail
    }
    return render(request,'book_temps/book_detail.html', context)

def borrow(request, pk):
    # if Borrow > 2:
    #     messages.success(request, ("You cant borrow more than 2 books at a time"))
    #     return redirect('library:book_detail')

    borrowbook = Book.objects.get(pk= pk)
    form = BorrowForm(request.POST or None)
    if request.method == "POST":
        if borrowbook.status == "Unavailable":
            messages.success(request, ("Oops....book is unavailable, please try again someother time"))
            return  redirect('library:message')
        if form.is_valid():
            # if borrowbook.status == "Unavailable":
            #     messages.success(request, ("Oops....book is unavailable, please try again someother time"))
            form.save()
            messages.success(request, ("You've successfully reserved a book,you are required to get it in the next 24 hours from the library.Check your activity"))
            borrowbook.status = "Unavailable"
            borrowbook.save() 
            return redirect ('library:activity') 
    #instance=borrowbook
    context = {
        'form': form
    }
    return render(request, 'book_temps/borrow.html',context)


def urlmessage(request):
    return render(request, 'book_temps/urlmessage.html',{})
        
    

def activity(request):
    laforms = Borrow.objects.all
    context ={
        'laforms' : laforms
    }
    return render(request, 'book_temps/activity.html',context)


    

library/templates/book_temps/activity.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends "main.html" %}
    {% load static %}
    {% block page_content %}
    <br><br>
    <center>
        <h1>your activity</h1>
        <br><br>
        <p>{% if messages %}
            {% for message in messages %}
             {{message}}
            {% endfor %}
           {% endif %}
        <table border="2">
            <thead>
                <tr>
                    <th>User</th>
                    <th>Email address</th>
                    <th>Title</th>
                    <th>Borrow Date</th>
                    <th>Return date</th>
                    <th>Days Remaining</th>
                    <th>Fine</th>
                </tr>
            </thead>
            <tbody>
                {% for aform in laforms %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ aform.email_address }}</td>
                    <td>{{ aform.book_title }}</td>
                    <td>{{ aform.borrow_date }}</td>
                    <td>{{ aform.return_date }}</td>
                    <td>{{ aform.days_remaining }}</td>
                    <td>{{ aform.Fine }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
       
    </center>
    {% endblock %}
</body>
</html>

library/templates/book_temps/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% extends "main.html" %}
    {% load static %}
    
</head>
<body>
    {% block page_content %}
    <br>
    <br>
    <p class="pbook_detail">{{ detail.title }} was published on {{ detail.publication_date }}</p>
    <div class="rowbook_detail">
        <div>
            <img class="imgbook_detail" src="{{detail.cover_photo.url}}" alt="">
        </div>
        
        <div class="contentbook_detail">
            <h5>Subject</h5>
            <p>{{ detail.subject_area }}</p>
            <h5>Book details</h5>
            <p>{{detail.description}}</p>
            <h5>Author</h5>
            <p>{{detail.author}}</p>
            <br>
            <a class="borrowlink" href="{% url 'library:borrow' detail.pk  %}">Borrow</a>
        </div>
    </div>
    <p>{% if messages %}
        {% for message in messages %}
         {{message}}
        {% endfor %}
       {% endif %}
    {% endblock %}
</body>
</html>

library/templates/book_temps/book_overview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% extends "main.html" %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    {% block page_content %}
    <br>
    <br>
    <div class="flex-row">
        {% for book in books %}
        <div class="cardshape">
            <img class="overviewimg"  src="{{book.cover_photo.url}}" alt= "bookcover">
                <h5><strong>{{ book.title }}</strong></h5>
                <p>Subject: {{ book.subject_area }}</p>
                <div class="aboutlinkdiv"><a class="aboutlink" href= "{% url 'library:book_detail' book.pk %}">About</a></div>
        </div>     
        {% endfor %}      
    </div>
    {% endblock %}
</body>
</html>

library/templates/book_temps/borrow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends "main.html" %}
    {% load static %}
    {% block page_content %}
    <br><br>
    <center>
        <h1>Confirm your details below to secure the book</h1>
        <p>{% if messages %}
            {% for message in messages %}
             {{message}}
            {% endfor %}
           {% endif %}
       </p>
       
        <br><br>
        <form method= POST class="login">
            <br>
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" value="Submit" class="form-button">
            <br>
            <a font-size="20px" href="{% url 'library:activity' %}">see activity </a>
        </form>

         


    </center>
    {% endblock %}
</body>
</html>

library/templates/book_temps/urlmessage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>{% if messages %}
        {% for message in messages %}
         {{message}}
        {% endfor %}
       {% endif %}
</body>
</html>